name: f_count
description: A dart equivalent of console.count() in JS
version: 0.0.1
homepage: https://github.com/Chinmay-KB/f_count

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  stack_trace: ^1.10.0
