name: f_count
description: A dart equivalent of console.count() in JS. This can be used to check for unwanted re-renders inside the build method of a widget
version: 0.1.0
homepage: https://github.com/Chinmay-KB/f_count

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: ^3.0.2
  stack_trace: ^1.10.0

dev_dependencies: 
  very_good_analysis: ^2.4.0

